services:
  frontend:
    build:
      context: ./frontend
    environment:
      VITE_SOCKET_URI: ${VITE_SOCKET_URI}
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app